In [1]:
import numpy as np

In [2]:
L=[1,2,3]

In [3]:
A=np.array(L)

In [5]:
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [6]:
type(A)

numpy.ndarray

In [10]:
L[0:2]
A[0:2]

array([1, 2])

In [16]:
L2 =[[1, 2], [3, 4]]
A2 = np.array(L2)

In [17]:
print(L2)
print(A2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [20]:
#Arrays de ceros y unos
zeros_array=np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
ones_array=np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#Arrays de rangos
range_array=np.arange(10)
print("Range Arrays: ",range_array)

Range Arrays:  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Arrays espaciados linealmente
linspace_array = np.linspace(0, 1, num=5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


[1, 2]